<?php
/** @var NetsuiteInternalId $block */
use Echidna\NetsuiteOrderSyc\Block\Adminhtml\Order\View\NetsuiteInternalId;
?>
<?php $order = $block->getOrder(); ?>
<?php if (isset($order)) : ?>
    <?php if ($netsuiteInternalId = $block->getNetsuiteInternalId($order)) : ?>
        <th><?php echo $block->escapeHtml(__('Netsuite Internal Id')) ?></th>
        <td> <?php echo $block->escapeHtml($netsuiteInternalId); ?></td>
    <?php endif; ?>
<?php endif; ?>
