<form  method="post" id="form-validate" class="form" action="<?php echo $block->getPostUrl(); ?>">
    <div>
        <label for="query" class="label">Please enter the Query</label></br>
        <div class=control">
            <textarea name="comment" cols="50" rows="25" class="textarea"></textarea>
        </div>
    </div>
    <div>
        <button name="submit" class="action primary" type="submit"><span>Submit</span></button>
    </div>
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
</form>