<form method="post" id="transaction-form" class="cc_transaction_form" action="<?php echo $block->getFormAction(); ?> >
 <section class="admin__page-section-checktransactionId">
<div id="check-transaction-id" class="admin__page-section-content">
    <table class="data-table admin__table-secondary check-transaction-id-table">
        <tbody>
        <tr>
            <label for="cc-transaction-id" class="label">Transaction Id:</label>
            <input type="text"
                   id="cc-transaction-id"
                   name="cc_transaction_id"
                   class="required-entry" placeholder="Transaction Id" required/><br><br>
        </tr>
        </tbody>

    </table>
    <div>
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
        <div id="transaction-missing" style ="color: red"></div>
        <div id="went-wrong" style ="color: red"></div>
        <div id ="success-message" style = "color:green"></div>
        <div id ="increment-id" style= "color:#e85c23"></div><br><br>
        <div id ="increment-id-place-after"style="color:#e85c23"></div>
    </div>
</div>
</section>
</form>
<br>
<br>
<div id="formOpen" style="display: none">
    <form  method="post" id="placeorder-form" class="placeorder-form" action="<?php echo $block->getFormAction(); ?>>
      <section class="admin__page-section-createorder">
    <table class="data-table admin__table-secondary createorder-table">
        <tbody>
        <tr>
            <label for="email" class="label">Email:</label>
            <input type="text"
                   id="email-id"
                   name="email-id"
                   class="required-entry" required/><br><br>

        </tr>
        <tr>
            <label for="grandtotal" class="label">Amount:</label>
            <input type="text"
                   id="grandtotal"
                   name="grandtotal"
                   class="required-entry" required/><br><br>

        </tr>
        <tr>
            <label for="forstores" class="label">Store:</label>
            <select name="forstores" required>
                <?php
                foreach($block->getStoreCode() as $storeCode) {?>
                    <option value="<?php echo $storeCode;?>"><?php echo $storeCode;?></option>
                <?php }?>
            </select><br><br>

        </tr>
        <tr>
            <label for="cardnumber" class="label">Card Number(Enter the last 4 digit):</label>
            <input type="text"
                   id="cardnumber"
                   name="cardnumber"
                   class="required-entry" required/><br><br>

        </tr>
        <tr>
            <label for="forcardTypes" class="label">Card Types:</label>
            <select name="forcardTypes" required>
                <?php
                foreach($block->getCardTypes() as $cardType) {?>
                    <option value="<?php echo $cardType;?>"><?php echo $cardType;?></option>
                <?php }?>
            </select><br><br>
        </tr>
        <tr>
            <label for="referenceNumber" class="label">Reference Number:</label>
            <input type="text"
                   id="referenceNumber"
                   name="referenceNumber"
                   class="required-entry"
                   required/><br><br>

        </tr>
        <tr>
            <label for="expirydate" class="label">Expiry Date:</label>
            <input type="text"
                   id="expiry"
                   name="expiry"
                   class="required-entry"
                   required/><p class="expiry_date"><comment>eg:11/20</comment></p><br><br>

        </tr>
        <tr>
            <label for="skus-createorder" class="label">Skus(Enter the Quantity and sku with comma seperated):</label>

            <input type="text"
                   id="skus-createorder"
                   name="skus-createorder"
                   class="required-entry" required/>
            <p class="sku_comment"><comment>eg:1-213098511/1-213097966</comment></p><br><br>

        </tr>
        </tbody>
    </table>
    </section>
    <div>
        <div id="success-message-place" style ="color: green"></div>
        <div id="went-wrong-place" style ="color: red"></div>
        <div id ="increment-id-place"style="color:#e85c23"></div>
        <br>
        <br>
        <input class="primary place-order" id="place-order" type="submit" value="place-order">

    </div>
    </form>
</div>
<script>
    require([
        'jquery',
        'mage/url',
        'prototype'
    ], function(jQuery,url) {
        /**
         * check the Increment Id
         */
        jQuery("#cc-transaction-id").change(function () {
            if (jQuery('#transaction-form').length) {
                jQuery.ajax({
                    type: 'POST',
                    url: "<?php echo $block->getUrl('atgsupport/fugitive/checkincrementid'); ?>",
                    data: jQuery('#transaction-form').serialize(),
                    showLoader: true,
                    success: function (response) {
                        if(response.success && response.incrementId=="Please enter the transaction Id")
                        {
                            jQuery("#went-wrong").text("Please enter the transaction Id").effect("bounce");
                            jQuery("#success-message").css("display", "none");
                            jQuery("#increment-id").css("display","none");
                            jQuery("#increment-id-place-after").css("display","none");
                            jQuery("#formOpen").css("display", "none");
                            return false;
                        }
                        else if(response.success && response.incrementId)
                        {
                            jQuery("#increment-id").text(response.incrementId).effect("bounce");
                            jQuery("#formOpen").css("display", "none");
                            jQuery("#success-message").css("display", "block");
                            jQuery("#increment-id").css("display","block");
                            jQuery("#went-wrong").css("display", "none");
                            jQuery("#success-message").text("There is already Order Created ");
                            jQuery("#increment-id-place-after").css("display","none");
                            return true;
                        }else if(response.success && response.incrementId==false) {
                            jQuery("#success-message").text("Create The Order").effect("bounce");
                            jQuery("#formOpen").css("display", "block");
                            jQuery("#success-message").css("display", "none");
                            jQuery("#increment-id").css("display","none");
                            jQuery("#increment-id-place-after").css("display","none");
                            jQuery("#increment-id-place").css("display", "none");
                            jQuery("#went-wrong").css("display", "none");
                            return true;
                        }
                        else if(response.error)
                        {
                            jQuery("#went-wrong").text("Something Went Wrong").effect("bounce");
                            return false;
                        }
                    }
                });
            }
        });
        //For Create Order
        jQuery("#place-order").click(function () {
            if (jQuery('#placeorder-form').length) {
                var data = jQuery('#placeorder-form').serializeArray()
                var transactionId =  jQuery("#cc-transaction-id").val();
                data.push({name: 'cc-transactionId', value:transactionId});
                jQuery.ajax({
                    type: 'POST',
                    url: "<?php echo $block->getUrl('atgsupport/fugitive/createorder'); ?>",
                    data:data ,
                    showLoader: true,
                    success: function (response) {
                        if(response.success && response.orderresponse)
                        {
                            jQuery("#increment-id-place").css("display","block");
                            jQuery("#increment-id-place").text(response.orderresponse).effect("bounce");
                            jQuery("#went-wrong-place").css("display", "none");
                            if(response.ordersuccess)
                            {
                                jQuery("#formOpen").css("display", "none");
                                jQuery("#increment-id-place-after").text(response.orderresponse).effect("bounce");
                                jQuery("#increment-id-place-after").css("display","block");
                            }
                            return true ;
                        }else if(response.error)
                        {
                            jQuery("#went-wrong-place").css("display","block");
                            jQuery("#went-wrong-place").text("something went wrong while creating the order").effect("bounce");
                            jQuery("#increment-id-place").css("display", "none");
                            return false;
                        }

                    }
                });
            }
        });
    });
</script>
